language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_script:
  # http://about.travis-ci.org/docs/user/database-setup/
  - composer install
  - sudo apt-get -y install sphinxsearch
  - sudo chmod 777 /usr/bin/searchd
  - sudo chmod 777 /usr/bin/indexer
  - mysql -e 'create database testDB;' > /dev/null
  - mysql -u testDB < config/movies.sql
  - indexer --config config/sphinx.conf --rotate --all