language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_script:
  # http://about.travis-ci.org/docs/user/database-setup/
  - composer install
  - sudo apt-get -y install sphinxsearch
  - mysql -e 'create database facet_sphinx;' > /dev/null
services:
  - redis-server
  - memcached